apiVersion: v1
kind: Service
metadata:
  name: bootnode
  namespace: eth
  labels:
    app: bootnode
    project: devday
spec:
  selector:
    app: bootnode
    project: devday
  clusterIP: None
  ports:
  - name: discovery
    port: 30301
    protocol: UDP
  - name: http
    port: 8080
