apiVersion: apps/v1
kind: Deployment
metadata:
  name: bootnode-registrar
  namespace: eth
  labels:
    app: bootnode-registrar
    project: devday
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: bootnode-registrar
      project: devday
  template:
    metadata:
      labels:
        app: bootnode-registrar
        project: devday
    spec:
      containers:
      - name: bootnode-registrar
        image: jpoon/bootnode-registrar:v1.0.0
        imagePullPolicy: IfNotPresent
        env:
        - name: BOOTNODE_SERVICE
          value: "bootnode.eth.svc.cluster.local"
        ports:
        - containerPort: 9898