apiVersion: v1
kind: Service
metadata:
  name: bootnode-registrar
  namespace: eth
  labels:
    app: bootnode-registrar
    project: devday
spec:
  selector:
    app: bootnode-registrar
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 9898