apiVersion: apps/v1
kind: Deployment
metadata:
  name: ethstats
  namespace: eth
  labels:
    app: ethstats
    project: devday
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: ethstats
      project: devday
  template:
    metadata:
      labels:
        app: ethstats
        project: devday
    spec:
      containers:
      - name: ethstats
        image: ethereumex/eth-stats-dashboard:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 3000
        env:
        - name: WS_SECRET
          valueFrom:
            secretKeyRef:
              name: ethstats-secret
              key: WS_SECRET