apiVersion: v1
kind: Service
metadata:
  name: ethstats
  namespace: eth
  labels:
    app: ethstats
    project: devday
spec:
  selector:
    app: ethstats
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http