apiVersion: v1
kind: Service
metadata:
  name: geth-tx
  namespace: eth
  labels:
    app: geth-tx
    project: devday
spec:
  selector:
    app: geth-tx
    project: devday
  type: LoadBalancer
  ports:
  - name: rpc
    port: 8545
  - name: ws
    port: 8546