apiVersion: apps/v1
kind: Deployment
metadata:
  name: ethstats
  labels:
    app: ethereum
    component: ethstats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ethereum
      component: ethstats
  template:
    metadata:
      labels:
        app: ethereum
        component: ethstats
    spec:
      containers:
        - name: ethstats
          image: ethereumex/eth-netstats:latest
          command: ["npm"]
          args: ["start"]
          ports: 
            - containerPort: 3000
              name: web
          env:
            - name: WS_SECRET
              value: secret
          resources:
            requests:
              cpu: "25m"
              memory: "150Mi"
            limits:
              cpu: "75m"
              memory: "500Mi"

